In [41]:
import numpy as np 
import pandas as pd 

In [42]:
df = pd.read_csv('spam.csv')

In [43]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [44]:
df['Category'].value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [45]:
df['spam'] = df['Category'].apply(lambda x : 1 if x == 'spam' else 0)

In [46]:
import sklearn

In [47]:
x = df['Message']
y = df['spam']
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [48]:
x_test.shape

(1115,)

In [49]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()

x_trainCV = v.fit_transform(x_train.values) ## This will make a bag of words
 

In [50]:
type(x_trainCV)

scipy.sparse._csr.csr_matrix

In [51]:
x_testCV = v.transform(x_test.values)

In [52]:
x_trainNP =  x_trainCV.toarray()
x_testNP =  x_trainCV.toarray()

In [53]:
type(x_trainNP)

numpy.ndarray

In [54]:
print(v.vocabulary_)

{'reply': 5687, 'to': 6888, 'win': 7474, '100': 258, 'weekly': 7396, 'where': 7437, 'will': 7471, 'the': 6773, '2006': 354, 'fifa': 2805, 'world': 7555, 'cup': 2106, 'be': 1271, 'held': 3364, 'send': 5980, 'stop': 6460, '87239': 694, 'end': 2568, 'service': 5999, 'hello': 3369, 'sort': 6304, 'of': 4854, 'out': 4976, 'in': 3603, 'town': 6959, 'already': 924, 'that': 6770, 'so': 6252, 'dont': 2395, 'rush': 5825, 'home': 3441, 'am': 934, 'eating': 2504, 'nachos': 4650, 'let': 4057, 'you': 7662, 'know': 3926, 'eta': 2627, 'how': 3487, 'come': 1902, 'guoyang': 3258, 'go': 3140, 'tell': 6711, 'her': 3384, 'then': 6784, 'told': 6904, 'hey': 3392, 'sathya': 5881, 'till': 6856, 'now': 4808, 'we': 7372, 'dint': 2323, 'meet': 4392, 'not': 4797, 'even': 2638, 'single': 6147, 'time': 6857, 'can': 1629, 'saw': 5894, 'situation': 6164, 'orange': 4945, 'brings': 1509, 'ringtones': 5763, 'from': 2993, 'all': 911, 'chart': 1733, 'heroes': 3387, 'with': 7502, 'free': 2958, 'hit': 3411, 'each': 2485, 'wee

In [55]:
np.where(x_trainNP[0] != 0)

(array([ 258,  354,  694, 1271, 2106, 2568, 2805, 3364, 5687, 5980, 5999,
        6460, 6773, 6888, 7396, 7437, 7471, 7474, 7555], dtype=int64),)

In [56]:
## Now we shall be training our naive bayes model

In [57]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(x_trainCV, y_train)

MultinomialNB()

In [58]:
prediction = model.predict(x_testCV)

In [59]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

print("The Accuracy is: ", accuracy_score(y_test, prediction))

The Accuracy is:  0.9919282511210762


In [60]:
print("The classification report for this naive bayes model is: \n", classification_report(y_test, prediction))

The classification report for this naive bayes model is: 
               precision    recall  f1-score   support

           0       0.99      1.00      1.00       966
           1       1.00      0.94      0.97       149

    accuracy                           0.99      1115
   macro avg       1.00      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [61]:
print("The confusion matrix for this is: \n", confusion_matrix(y_test, prediction))

The confusion matrix for this is: 
 [[966   0]
 [  9 140]]


In [71]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20 percent discount on parking, exclusive offer just for you. Dont miss this reward!',
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)